#!/usr/bin/env ruby -w

$LOAD_PATH.unshift(File.expand_path(File.join(File.dirname(__FILE__), "..", "lib")))
require 'webconnex_api'


require 'rubygems'
gem 'activesupport', '~> 7.0'
require 'active_support/core_ext/object/blank'

if ENV["WEBCONNEX_API_KEY"].blank?
  raise "Error: environment missing WEBCONNEX_API_KEY"
end
WEBCONNEX_API_KEY = ENV["WEBCONNEX_API_KEY"]


def main
  ARGV.each do |show_name|
    print_inventory_report_for_show_name(show_name)
    puts "\n\n"
  end
end

def print_inventory_report_for_show_name(name)
  forms = WebconnexAPI::Form.all
  show = forms.find { |f| f.name == name }
  raise "No show found called #{name.inspect}" if show.nil?

  puts "#{name}:\n\n"

  last_date = nil
  show.inventory_records.sort_by(&:event_time).each do |ir|
    this_date = ir.event_time.to_date
    if !last_date.nil? && this_date - last_date > 1
      puts "\n\n"
    elsif !last_date.nil? && this_date != last_date
      puts
    end
    if last_date.nil? || last_date != this_date
      print this_date.strftime("    %a, %b %e at ")
    elsif last_date == this_date
      print "                   "
    end

    print ir.event_time.strftime("%l:%M%P: ")
    puts "#{ir.sold.to_s.rjust(ir.quantity.to_s.length)} / #{ir.quantity}"
    last_date = this_date
  end
end

main
